package com.aoc2024.core.day;

import com.aoc2024.api.model.Input;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Day8Test extends DayTestBase {

    private static final Day8 underTest = new Day8();

    @Override
    Day getUnderTest() {
        return underTest;
    }

    @Override
    String getInputPt1() {
        return """
            ............
            ........0...
            .....0......
            .......0....
            ....0.......
            ......A.....
            ............
            ............
            ........A...
            .........A..
            ............
            ............""";
    }

    @Override
    String getInputPt2() {
        return """
            ............
            ........0...
            .....0......
            .......0....
            ....0.......
            ......A.....
            ............
            ............
            ........A...
            .........A..
            ............
            ............""";
    }

    @Override
    String expectedPt1() {
        return "14";
    }

    @Override
    String expectedPt2() {
        return "34";
    }

    @Test
    void part1_outOfBounds() {
        Input input = TestHelper.convertToInput("""
                                                    a.a.
                                                    a...""");
        assertEquals("0", underTest.getAnswer1(input));
    }

    @Test
    void part2Small() {
        Input input = TestHelper.convertToInput("""
                                                    T.........
                                                    ...T......
                                                    .T........
                                                    ..........
                                                    ..........
                                                    ..........
                                                    ..........
                                                    ..........
                                                    ..........
                                                    ..........""");
        assertEquals("9", underTest.getAnswer2(input));
    }

}
